# Generated by Django 5.1.1 on 2024-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
